apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: ball
spec:
  version: "v0.1.0"
  homepage: "https://github.com/robolague/kubectl-ball"
  shortDescription: "Run kubectl commands across multiple clusters with fzf selection"
  description: |
    kubectl-ball helps you run kubectl commands across multiple clusters using fzf-based selection.
    You can persist selections, share namespace settings, grep across clusters, format output (e.g., JSON/YAML), and run commands in parallel.

  platforms:
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    uri: https://github.com/robolague/kubectl-ball/releases/download/v0.1.0/kubectl-ball_linux_amd64.tar.gz
    sha256: "<REPLACE_WITH_LINUX_SHA256>"
    bin: kubectl-ball

  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    uri: https://github.com/robolague/kubectl-ball/releases/download/v0.1.0/kubectl-ball_darwin_amd64.tar.gz
    sha256: "<REPLACE_WITH_DARWIN_SHA256>"
    bin: kubectl-ball
