name: Lint

on:
  push:
    branches: [ main, first-commit-code ]
  pull_request:
    branches: [ main, first-commit-code ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
      - name: Download dependencies
        run: go mod download
      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.58.0
      - name: Run golangci-lint
        run: $(go env GOPATH)/bin/golangci-lint run 