name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin]
        goarch: [amd64]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.24

    - name: Build binaries
      run: |
        mkdir -p dist
        GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o dist/kubectl-ball_${{ matrix.goos }}_${{ matrix.goarch }} main.go

    - name: Create archive
      run: |
        cd dist
        tar -czf kubectl-ball_${{ matrix.goos }}_${{ matrix.goarch }}.tar.gz kubectl-ball_${{ matrix.goos }}_${{ matrix.goarch }}

    - name: Upload release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          dist/kubectl-ball_*.tar.gz
